# Generated by Django 4.0.2 on 2022-04-27 01:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('author', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_creation', models.DateTimeField(auto_now_add=True)),
                ('changed', models.DateTimeField(auto_now=True)),
                ('up_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('status', models.CharField(choices=[('racunho', 'Rascunho'), ('publicado', 'Publicado')], default='rascunho', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
